### ISSUE TITLE
Fire control TODO list

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#140]
For the AJS mostly.

Weapon panel:
- [ ] 3D model
- [ ] Weapon selector knob.
Implementing it requires to have the ground crew weapon panel in one form or another.
My current plan is to make the ground crew weapon panel as a canvas dialog, and have the loadout dialog do the ground crew settings automatically. This way, one can either
  - Use custom loadouts (with Equipment - Fuel and Payload), and take care of ground crew settings manually.
  - Or use preset loadouts (with AJS-37 - Fuel/Loadout), and never care about the ground crew panel.
- [ ] Distance selector
  - [ ] Firing interval for bombs
  - [ ] Target wingspan for A/A
- [ ] SERIE/IMPULS switch. Should affect
  - [ ] Rb 04, Rb 15
  - [ ] ARAK long range aiming mode.
  - training bombs
- MÅLVAL switch (Rb 04 and Rb 15 search mode). Won't be implemented in the foreseeable future.

Weapon behaviour:
- [ ] In general, many weapons can be fired without being in mode ANF
- [ ] Rb 04
  - [ ] Firing in modes NAV, SPA, LANDNING
  - [ ] Release envelop (commended altitude, altitude warning, ...)
- [ ] Rb 15
  - [ ] All the waypoint navigation
  - [ ] Firing in mode NAV, SPA. In that case, it just follows a straight trajectory (pretty much the current behaviour).
  - [ ] Release envelop (commended altitude, altitude warning, ...)
- [ ] Rb 05.
  - [ ] Battery dies 40s after unsafing the trigger. Unsafing and re-safing makes the missile unusable. (Do I want to be an ***hole by implementing this?)
  - [ ] Disable proximity fuse if not fired in A/A mode (weapon selector knob).
- [ ] Rb 75. 
  - [ ] Locking on targets through EP 13 (controlled with radar stick). Very hard, I have no idea how to deal with this.
  - [ ] Firing in mode NAV.
- [ ] AKAN/ARAK
  - [ ] Firing in mode NAV.
  - [ ] ARAK always fire all rockets.
- [ ] m/71
  - [ ] Firing in mode NAV
  - [ ] Firing interval selector
- [ ] m/90
  - [ ] Waypoint target
  - [ ] Firing in mode NAV/SPA
  - [ ] Release envelop computation (going to be hard).

Then, there is everything related to displays. Which is going to be fun.
