### ISSUE TITLE
Flight Manual TODO list

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#143]
Remark: manual source code is in this repo
https://github.com/NikolaiVChr/flightgear-viggen-masters/tree/master/Documentation

By chapters.

Part 1: Aircraft description
- Instrumentation and Indicators
  * [ ] Add pictures (instruments done, need to add a few for the indicators).
  * [ ] Missing: trim indicators, brake pressure, cabin pressure, oxygen. Anything else?
- Control panels.
  * [ ] Datapanel and navpanel. I'm thinking of only giving an overview of the datapanel here,
then detailed procedures in the 'Operation' part, plus a appendix for datapanel usage quick reference.
  * [ ] Radio channel selectors (including datalink)
  * [ ] RWR (just for the volume knob?)
  * [ ] Add pictures
- Displays.
  * [ ] HUD (high priority)
  * [ ] MI (high priority)
  * [ ] TI (will take a bit more time)
  * [ ] CI ? Do I want to add it now, or wait until a rework?
- Systems. Not very high priority IMO. Things like electrical, hydraulics, ...

Part 2: Operation
- [ ] Standard procedures (the normal checklists)
- [ ] Emergency procedures
- [ ] Navigation procedures. Probably follow the order of a flight (like in AJS SFI volume 3):
e.g. preparation, takeoff, waypoint navigation, landing

Appendixes:
- [ ] Swedish/English Viggen dictionary
- [ ] Datapanel cheat sheet
