### ISSUE TITLE
Radios TODO list

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#170]
- [x] Make 3D model for AJS FR22 control panel.
- [x] Fix AJS frequency selection panel. (only one switch for AM/FM, no secondary display).
- [x] Improve JA frequency selectors. For instance the JA37 manual mentions that in BAS or NR mode, pressing a button will change the last channel character (very useful: the first two indicate the base / aircraft group, and the last is used for the channel within this base / group). Need to read the manual in detail.
- [x] Fix allowed frequency band. (In particular UHF).
- [ ] Not sure what to do with AM/FM
- [x] Implement all frequency selection methods:
  * [x] The FR24/29 panel selects one of the following operation mode:
    - H : standby radio on guard frequency
    - E,F,G : standby radio on fixed frequencies (which ones?)
    - N : main radio
    - N+L : main radio + standby radio listening to guard frequency
  * [x] For the main radio, the frequency is selected with the FR22 / KV1 panel. There are several options:
    - direct frequency input
    - pre-programmed channel number
    - pre-programmed airport channel
    - (AJS only?) buttons for guard channel and 3 special pre-programmed channels
    - (AJS only?) channels E,F,G when base knob is in position ALLM
  * [x] The JA FR31 radio is like a duplicate of the main radio, working independently.
- [x] For all the preprogrammed channels:
  * [x] Allow loading text configuration files
  * [ ] A dialog to set channels in sim? That seems like a bad idea, one can define around 1000 channels.
  * [ ] In sim frequencies sheet would be nice.
- [x] Checks
  * [x] volume knobs
    - [x] left wall knob controls sidewinder/rb71/rb99 sound.
      * [x] Correct for the AJS
      * [ ] For the JA, it should be on the radar panel instead.
      * [x] rb71/rb99 sounds are not a thing afaik — this sound is for radar lock.
      * [x] property names `ja37/radio/fr29/knob-vol` and `ja37/sound/helmet` suck — new properties: `ja37/sound/{warnings,ir}-volume`
    - [x] Fr 29 volume knob: there should actually be 2 knobs
      * [x] Inner knob controls comm radio volume (really need that, there is no control right now)
      * [x] Outer knob controls warnings volume
      * For the AJS the corresponding Fr 24 panel has a knob for comm volume, nothing for warnings. It probably doesn't have the JA warnings in the first place, but that's a different question. As far as radios are concerned, it's okish to keep it as the JA.
    - [x] RWR panel knob controls RWR warnings. AJS could use a different panel, but that's a different problem.
    - [x] FR31 panel knob controls FR31 volume.
  * [x] power
- [x] FGcom-mumble compatibility:
  * [x] define property `instrumentation/comm[i]/tx-power` (watts)
